# Generated by Django 5.2.8 on 2026-04-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('matched_keywords', models.TextField(blank=True)),
                ('missing_keywords', models.TextField(blank=True)),
                ('experience_score', models.IntegerField(default=0)),
                ('skills_score', models.IntegerField(default=0)),
                ('education_score', models.IntegerField(default=0)),
                ('certifications_score', models.IntegerField(default=0)),
                ('job_title_score', models.IntegerField(default=0)),
            ],
        ),
    ]
